# .travis.yaml

language: python

sudo: true

env:
  - LUA_VERSION="5.4" KONG_VERSION="2.3.2" LUA_RESTY_OPENIDC_VERSION="1.7.4"

script:
  - sudo -E bash ci/root.sh
  - . ci/setup.sh
  - . ci/run.sh

after_success:
  - luarocks install luacov-coveralls
  - luacov-coveralls
